export const FILTER_BY_STATUS = "FILTER_BY_STATUS"
export const ADD = "ADD"
export const REMOVE = "REMOVE"
export const EDIT = "EDIT"
export const SAVE_CHANGES = "SAVE_CHANGES"
export const CHANGE_STATUS = "CHANGE_STATUS"
export const OPEN_FORM = "OPEN_FORM"
export const CLOSE_FORM = "CLOSE_FORM"